version: '3'
services: 
 
    nginx-proxy:
        image: nginx:alpine
        container_name: nginx-proxy
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.11
        ports: 
            - 80:80
        volumes: 
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/conf.d:/etc/nginx/conf.d
    
    site-www:
        image: nginx:alpine
        container_name: site_www
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.12
        # ports: 
        #     - 80:80
        volumes:             
            - ./app/www/site.conf:/etc/nginx/conf.d/default.conf
            - ./app/www/public:/usr/share/nginx/html


    mariadb:
        image: mariadb:10.5.5
        container_name: ${MYSQL_CONTAINER_NAME}
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.5
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=${TZ}
        volumes: 
            - ./mysql/data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links: 
            - mariadb
        environment: 
            - PMA_HOST=${MYSQL_CONTAINER_NAME}
        ports: 
            - 8080:80