version: '3'
services: 
 
    nginx-proxy:
        image: nginx:alpine
        container_name: nginx-proxy
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.11
        ports: 
            - 80:80
        volumes: 
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/conf.d:/etc/nginx/conf.d
    
    site-www:
        image: nginx:alpine
        container_name: site_www
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.12
        # ports: 
        #     - 80:80
        links: 
            - php-fpm
        volumes:             
            - ./app/www/site.conf:/etc/nginx/conf.d/default.conf
            - ./app/www/public:/app

    site-api:
        image: nginx:alpine
        container_name: site_api
        links: 
            - php-fpm
        volumes:             
            - ./app/api/site.conf:/etc/nginx/conf.d/default.conf
            - ./app/api/public:/app

    php-fpm:
        build: 
            context: ./build/php
            args:
                - TZ=${TZ}
        container_name: php
        environment:
            - TZ=${TZ}
        volumes: 
            - ./app/www/public:/app/www   
            - ./app/api/public:/app/api    

    # php7-fpm:
    #     image: php:7.4-fpm-alpine
    #     container_name: php7
    #     volumes: 
    #         - ./app/api/public:/app/api
    # php-fpm:
        # image: php:5.6-fpm-alpine
        # image: php:7.4-fpm-alpine
        # container_name: php
        # volumes: 
        #     - ./app/www/public:/app/www

    mariadb:
        image: mariadb:10.5.5
        container_name: ${MYSQL_CONTAINER_NAME}
        # networks: 
        #     default:
        #         ipv4_address: 10.5.0.5
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=${TZ}
        volumes: 
            - ./mysql/data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links: 
            - mariadb
        environment: 
            - PMA_HOST=${MYSQL_CONTAINER_NAME}
            - TZ=${TZ}
        ports: 
            - 8080:80

networks: 
    default:
        driver: bridge
        ipam: 
            config: 
                - subnet: 10.5.0.0/24